name: 'Policy Linter'
description: 'Validate agent-treasury policy JSON against schema and safety rules'
inputs:
  policy:
    description: 'Path to the policy JSON file'
    required: true
  report:
    description: 'Path to write the JSON report'
    required: true
  strict:
    description: 'Treat warnings as errors (true/false)'
    required: false
    default: 'false'
  sarif:
    description: 'Optional path to write SARIF output (for GitHub Code Scanning)'
    required: false
  artifact:
    description: 'Optional artifact path to anchor SARIF findings (defaults to policy path)'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install dependencies
      shell: bash
      run: npm ci
    - name: Build CLI
      shell: bash
      run: npm run build
    - name: Run linter
      shell: bash
      env:
        POLICY: ${{ inputs.policy }}
        REPORT: ${{ inputs.report }}
        STRICT: ${{ inputs.strict }}
        SARIF: ${{ inputs.sarif }}
        ARTIFACT: ${{ inputs.artifact }}
      run: |
        set -euo pipefail
        CMD=(node dist/cli.js "$POLICY" --report "$REPORT")
        if [[ -n "${SARIF}" ]]; then
          CMD+=(--sarif "$SARIF")
          if [[ -n "${ARTIFACT}" ]]; then CMD+=(--artifact "$ARTIFACT"); fi
        fi
        if [[ "${STRICT}" == "true" ]]; then CMD+=(--strict); fi
        echo "Running: ${CMD[*]}"
        "${CMD[@]}"
