name: CI (Policy Linter composite action)

on:
  pull_request:
  push:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps
        run: npm ci
      - name: Build CLI
        run: npm run build
      - name: Run action on good policy
        uses: ./.github/actions/policy-linter
        with:
          policy: samples/policy.good.json
          report: report.good.json
          strict: 'false'
      - name: Run action on bad policy (strict; expect non-zero)
        uses: ./.github/actions/policy-linter
        with:
          policy: samples/policy.bad.json
          report: report.bad.json
          strict: 'true'
        continue-on-error: true
      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: policy-linter-action-reports
          path: |
            report.good.json
            report.bad.json
