name: Policy Lint (build + run)

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build CLI
        run: npm run build

      - name: Run Policy Linter (good)
        run: node dist/cli.js samples/policy.good.json --report report.good.json

      - name: Run Policy Linter (bad, strict; expect non-zero)
        run: |
          set +e
          node dist/cli.js samples/policy.bad.json --strict --report report.bad.json
          echo "exit_code=$?" >> $GITHUB_OUTPUT
        id: bad

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: policy-linter-reports
          path: |
            report.good.json
            report.bad.json
